const CURRENCY = "MAD";

const resinProducts = [
  { id: "resin-01", cat: "art7: 9:00 -", price: 550, img: "images/resin/resin-01.jpeg",
    name: { en: "Wedding Bouquet Preservation", ar: "حفظ باقة الزفاف", fr: "Préservation de bouquet de mariage" } },
  { id: "resin-02", cat: "art", price: 450, img: "images/resin/resin-02.jpg",
    name: { en: "Resin Artwork", ar: "تحفة راتنجية", fr: "Œuvre en résine" } },
  { id: "resin-03", cat: "art", price: 420, img: "images/resin/resin-03.jpeg",
    gallery: ["images/resin/resin-04.jpeg"],
    name: { en: "Ocean Resin Art", ar: "فن بحر الراتنج", fr: "Art océanique en résine" } },
  { id: "resin-05", cat: "decor", price: 250, img: "images/resin/resin-05.jpeg",
    gallery: ["images/resin/resin-06.jpeg"],
    name: { en: "Resin Coasters", ar: "حوامل أكواب راتنج", fr: "Sous-verres en résine" } },
  { id: "resin-07", cat: "art", price: 350, img: "images/resin/resin-07.jpeg",
    name: { en: "Resin Jewelry Box", ar: "علبة مجوهرات راتنج", fr: "Boîte à bijoux en résine" } },
  { id: "resin-08", cat: "decor", price: 320, img: "images/resin/resin-08.jpeg",
    name: { en: "Resin Vase", ar: "مزهرية راتنج", fr: "Vase en résine" } },
  { id: "resin-09", cat: "jewelry", price: 200, img: "images/resin/resin-09.jpeg",
    name: { en: "Resin Pendant", ar: "قلادة راتنج", fr: "Pendentif en résine" } },
  { id: "resin-10", cat: "decor", price: 280, img: "images/resin/resin-10.jpeg",
    name: { en: "Resin Candle Holder", ar: "حامل شموع راتنج", fr: "Porte-bougie en résine" } },
  { id: "resin-11", cat: "decor", price: 480, img: "images/resin/resin-11.jpeg",
    name: { en: "Resin Decor Clock", ar: "ساعة ديكور راتنج", fr: "Horloge décorative en résine" } },
  { id: "resin-12", cat: "art", price: 650, img: "images/resin/resin-12.jpeg",
    gallery: ["images/resin/resin-13.jpeg"],
    name: { en: "Resin Sculpture", ar: "تمثال راتنج", fr: "Sculpture en résine" } },
  { id: "resin-14", cat: "art", price: 700, img: "images/resin/resin-14.jpeg",
    gallery: ["images/resin/resin-15.jpeg"],
    name: { en: "Resin Lamp Art", ar: "مصباح راتنج فني", fr: "Lampe artistique en résine" } },
  { id: "resin-16", cat: "jewelry", price: 150, img: "images/resin/resin-16.jpeg",
    name: { en: "Resin Keychain", ar: "سلسلة مفاتيح راتنج", fr: "Porte-clés en résine" } },
  { id: "resin-17", cat: "decor", price: 260, img: "images/resin/resin-17.jpeg",
    name: { en: "Resin Photo Frame", ar: "إطار صور راتنج", fr: "Cadre photo en résine" } },
  { id: "resin-18", cat: "decor", price: 340, img: "images/resin/resin-18.jpeg",
    name: { en: "Resin Decorative Bowl", ar: "طبق زينة راتنج", fr: "Bol décoratif en résine" } },
  { id: "resin-19", cat: "decor", price: 240, img: "images/resin/resin-19.jpg",
    name: { en: "Resin Coaster Set", ar: "طقم حوامل راتنج", fr: "Ensemble de sous-verres en résine" } },
  { id: "resin-20", cat: "art", price: 400, img: "images/resin/resin-20.jpeg",
    name: { en: "Name in Resin", ar: "اسم بالراتنج", fr: "Prénom en résine" } },
  { id: "resin-21", cat: "decor", price: 500, img: "images/resin/resin-21.jpeg",
    name: { en: "Quran Book Holder in Resin", ar: "حامل كتاب في الراتنج", fr: "Support de livre en résine" } }
];

const gypsumProducts = [
  { id: "gypsum-01", cat: "decor", price: 300, img: "images/gypsum/gypsum-01.jpeg",
    name: { en: "Classic Gypsum Vase", ar: "مزهرية جبس كلاسيكية", fr: "Vase classique en plâtre" } },
  { id: "gypsum-02", cat: "wallart", price: 450, img: "images/gypsum/gypsum-02.jpeg",
    name: { en: "Gypsum Wall Art", ar: "لوحة جدارية جبس", fr: "Art mural en plâtre" } },
  { id: "gypsum-03", cat: "decor", price: 350, img: "images/gypsum/gypsum-03.jpeg",
    name: { en: "Gypsum Decor Bowl", ar: "طبق ديكور جبس", fr: "Bol décoratif en plâtre" } },
  { id: "gypsum-04", cat: "molds", price: 280, img: "images/gypsum/gypsum-04.jpeg",
    name: { en: "Gypsum Craft Mold", ar: "قالب حرفي جبس", fr: "Moule artisanal en plâtre" } },
  { id: "gypsum-05", cat: "art", price: 250, img: "images/gypsum/gypsum-05.jpeg",
    name: { en: "Gypsum Figure", ar: "تمثال جبس", fr: "Figurine en plâtre" } },
  { id: "gypsum-06", cat: "decor", price: 220, img: "images/gypsum/gypsum-06.jpeg",
    name: { en: "Gypsum Candle Holder", ar: "حامل شموع جبس", fr: "Porte-bougie en plâtre" } },
  { id: "gypsum-07", cat: "wallart", price: 550, img: "images/gypsum/gypsum-07.jpeg",
    name: { en: "Gypsum Wall Panel", ar: "لوح جبس للجدار", fr: "Panneau mural en plâtre" } },
  { id: "gypsum-08", cat: "decor", price: 400, img: "images/gypsum/gypsum-08.jpeg",
    name: { en: "Gypsum Centerpiece", ar: "قطعة زينة مركزية جبس", fr: "Pièce centrale en plâtre" } },
  { id: "gypsum-09", cat: "decor", price: 380, img: "images/gypsum/gypsum-09.jpeg",
    name: { en: "Gypsum Decorative Vase", ar: "مزهرية ديكور جبس", fr: "Vase décoratif en plâtre" } },
  { id: "gypsum-10", cat: "art", price: 320, img: "images/gypsum/gypsum-10.jpeg",
    name: { en: "Hand-Painted Gypsum Art", ar: "فن جبس مرسوم يدوياً", fr: "Art en plâtre peint à la main" } },
  { id: "gypsum-11", cat: "decor", price: 260, img: "images/gypsum/gypsum-11.jpeg",
    name: { en: "Gypsum Ornament", ar: "زينة جبس", fr: "Ornement en plâtre" } },
  { id: "gypsum-12", cat: "decor", price: 300, img: "images/gypsum/gypsum-12.jpeg",
    name: { en: "Gypsum Flower Vase", ar: "مزهرية زهور جبس", fr: "Vase à fleurs en plâtre" } },
  { id: "gypsum-13", cat: "art", price: 180, img: "images/gypsum/gypsum-13.jpeg",
    name: { en: "Gypsum Mini Sculpture", ar: "تمثال جبس صغير", fr: "Mini sculpture en plâtre" } },
  { id: "gypsum-14", cat: "decor", price: 240, img: "images/gypsum/gypsum-14.jpeg",
    name: { en: "Gypsum Trinket Bowl", ar: "طبق جبس صغير", fr: "Coupelle en plâtre" } }
];

const giftProducts = [
  { id: "gift-01", cat: "wedding", price: 1100, img: "images/gifts/gift-01.jpg",
    name: { en: "Wedding Gift Set", ar: "طقم هدية زفاف", fr: "Ensemble cadeau de mariage" } },
  { id: "gift-02", cat: "birthday", price: 450, img: "images/gifts/gift-02.jpeg",
    name: { en: "Birthday Gift Box", ar: "علبة هدية عيد ميلاد", fr: "Boîte cadeau d'anniversaire" } },
  { id: "gift-03", cat: "birthday", price: 400, img: "images/gifts/gift-03.jpeg",
    name: { en: "Personalized Gift Frame", ar: "إطار هدية مخصص", fr: "Cadre cadeau personnalisé" } },
  { id: "gift-04", cat: "holiday", price: 500, img: "images/gifts/gift-04.jpeg",
    name: { en: "Holiday Gift Set", ar: "طقم هدية عيد", fr: "Ensemble cadeau de fête" } },
  { id: "gift-05", cat: "wedding", price: 600, img: "images/gifts/gift-05.jpeg",
    name: { en: "Romantic Gift Set", ar: "طقم هدية رومانسية", fr: "Ensemble cadeau romantique" } },
  { id: "gift-06", cat: "birthday", price: 350, img: "images/gifts/gift-06.jpeg",
    name: { en: "Resin Flower Gift", ar: "زهرة راتنج كهدية", fr: "Fleur en résine cadeau" } }
];

const featuredProducts = [
  resinProducts.find((p) => p.id === "resin-01"),
  resinProducts.find((p) => p.id === "resin-21"),
  giftProducts.find((p) => p.id === "gift-06")
].filter(Boolean);